#!/bin/bash

# 🎯 PiTech App Scaffolder - El 81% que necesitas
create_app_scaffold() {
    local app_name="${1:-my_app}"
    
    echo "🚀 Creando scaffold para: $app_name"
    
    mkdir -p "$app_name"/{src/{models,views,controllers},templates,static,scripts}
    
    # Estructura básica
    cat > "$app_name/app.py" << EOF
#!/usr/bin/env python3
# 🕸️ $app_name - Generated by PiTech Scaffolder
# El 81% de toda app web básica

from flask import Flask, render_template, request, jsonify
import json
import os

app = Flask(__name__)

# Configuración básica
app.config['SECRET_KEY'] = os.urandom(24)

@app.route('/')
def home():
    return render_template('base.html', title='$app_name')

@app.route('/api/data')
def api_data():
    return jsonify({"status": "ok", "message": "¡PiTech funciona!"})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
EOF

    # Requirements básico
    cat > "$app_name/requirements.txt" << EOF
Flask==2.3.3
Werkzeug==2.3.7
EOF

    # Script de despliegue
    cat > "$app_name/scripts/deploy.sh" << EOF
#!/bin/bash
echo "🕸️ Desplegando $app_name..."
pip install -r requirements.txt
python app.py
EOF

    chmod +x "$app_name/scripts/deploy.sh"
    
    echo "✅ Scaffold creado: $app_name"
    echo "🎯 Estructura del 81% lista para personalizar el 19% restante"
}

# Uso: ./pitech_scaffold.sh mi_app
create_app_scaffold "$@"
